export const GET_SCREEN_DATA_BY_AUDIENCES_REQUEST = "GET_SCREEN_DATA_BY_AUDIENCES_REQUEST";
export const GET_SCREEN_DATA_BY_AUDIENCES_SUCCESS = "GET_SCREEN_DATA_BY_AUDIENCES_SUCCESS";
export const GET_SCREEN_DATA_BY_AUDIENCES_ERROR = "GET_SCREEN_DATA_BY_AUDIENCES_ERROR";

export const GET_SCREENS_COST_DATA_REQUEST = "GET_SCREENS_COST_DATA_REQUEST";
export const GET_SCREENS_COST_DATA_SUCCESS = "GET_SCREENS_COST_DATA_SUCCESS";
export const GET_SCREENS_COST_DATA_ERROR = "GET_SCREENS_COST_DATA_ERROR";

export const GET_SCREENS_DATA_ADVANCE_FILTER_REQUEST = "GET_SCREENS_DATA_ADVANCE_FILTER_REQUEST";
export const GET_SCREENS_DATA_ADVANCE_FILTER_SUCCESS = "GET_SCREENS_DATA_ADVANCE_FILTER_SUCCESS";
export const GET_SCREENS_DATA_ADVANCE_FILTER_ERROR = "GET_SCREENS_DATA_ADVANCE_FILTER_ERROR";
