export const GET_SCREEN_DATA_BY_AUDIENCES_REQUEST =
  "GET_SCREEN_DATA_BY_AUDIENCES_REQUEST";
export const GET_SCREEN_DATA_BY_AUDIENCES_SUCCESS =
  "GET_SCREEN_DATA_BY_AUDIENCES_SUCCESS";
export const GET_SCREEN_DATA_BY_AUDIENCES_ERROR =
  "GET_SCREEN_DATA_BY_AUDIENCES_ERROR";

export const GET_SCREENS_COST_DATA_REQUEST = "GET_SCREENS_COST_DATA_REQUEST";
export const GET_SCREENS_COST_DATA_SUCCESS = "GET_SCREENS_COST_DATA_SUCCESS";
export const GET_SCREENS_COST_DATA_ERROR = "GET_SCREENS_COST_DATA_ERROR";

export const GET_SCREENS_DATA_ADVANCE_FILTER_REQUEST =
  "GET_SCREENS_DATA_ADVANCE_FILTER_REQUEST";
export const GET_SCREENS_DATA_ADVANCE_FILTER_SUCCESS =
  "GET_SCREENS_DATA_ADVANCE_FILTER_SUCCESS";
export const GET_SCREENS_DATA_ADVANCE_FILTER_ERROR =
  "GET_SCREENS_DATA_ADVANCE_FILTER_ERROR";

export const GET_SCREENS_PRICE_FOR_REGULAR_COHORT_REQUEST =
  "GET_SCREENS_PRICE_FOR_REGULAR_COHORT_REQUEST";
export const GET_SCREENS_PRICE_FOR_REGULAR_COHORT_SUCCESS =
  "GET_SCREENS_PRICE_FOR_REGULAR_COHORT_SUCCESS";
export const GET_SCREENS_PRICE_FOR_REGULAR_COHORT_ERROR =
  "GET_SCREENS_PRICE_FOR_REGULAR_COHORT_ERROR";

export const GET_SCREEN_SUMMARY_DATA_REQUEST =
  "GET_SCREEN_SUMMARY_DATA_REQUEST";
export const GET_SCREEN_SUMMARY_DATA_SUCCESS =
  "GET_SCREEN_SUMMARY_DATA_SUCCESS";
export const GET_SCREEN_SUMMARY_DATA_ERROR = "GET_SCREEN_SUMMARY_DATA_ERROR";

export const GET_SCREEN_SUMMARY_PLAN_TABLE_DATA_REQUEST =
  "GET_SCREEN_SUMMARY_PLAN_TABLE_DATA_REQUEST";
export const GET_SCREEN_SUMMARY_PLAN_TABLE_DATA_SUCCESS =
  "GET_SCREEN_SUMMARY_PLAN_TABLE_DATA_SUCCESS";
export const GET_SCREEN_SUMMARY_PLAN_TABLE_DATA_ERROR =
  "GET_SCREEN_SUMMARY_PLAN_TABLE_DATA_ERROR";

export const GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_REQUEST =
  "GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_REQUEST";
export const GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_SUCCESS =
  "GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_SUCCESS";
export const GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_ERROR =
  "GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_ERROR";
export const GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_RESET =
  "GET_SCREEN_DATA_CITY_WISE_FOR_UPLOAD_CREATIVES_RESET";
